CREATE TABLE  SCRAPPING_SITE(
 target_name	 TEXT,
 target_url TEXT,
 detail_target_url TEXT,
 category_big	 TEXT,
 category_middle TEXT,
 category_small TEXT,
 search_word   TEXT,
 create_date TEXT,
 recruit_title TEXT,
 company_name TEXT,
 detail_uri	 TEXT,
 task TEXT,
 employment_type TEXT,
 company_info TEXT,
 need_career TEXT,
 salary TEXT,
 apply_start_date, apply_end_date		 TEXT,
 work_place TEXT,
 main_service TEXT,
 work_info TEXT,
 career_requirements TEXT,
 preference TEXT,
 company_culture TEXT,
 team_env TEXT,
 need_doc TEXT,
 contact_people TEXT,
 hashtag TEXT,
id INTEGER,
 PRIMARY KEY(id)
)